# Generated by Django 2.1.5 on 2019-02-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=' ', max_length=50)),
                ('last_name', models.CharField(default=' ', max_length=50)),
                ('about_me', models.TextField(default=' ',max_length=350)),
                ('email_id', models.EmailField(default=' ', max_length=100)),
                ('phone_number', models.CharField(default=' ', max_length=13)),
            ],
            options={
                'ordering': ('first_name',),
            },
        ),
    ]
