# Generated by Django 2.1.5 on 2019-02-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20190215_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profile_pic',
            field=models.ImageField(max_length=255, null=True, upload_to='pics/'),
        ),
    ]
