# Generated by Django 2.1.5 on 2019-02-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20190215_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='profile_pic',
        ),
    ]
