# Generated by Django 2.1.5 on 2019-02-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_remove_userdetails_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='email_id',
            field=models.CharField(blank='True', default='', max_length=100),
        ),
    ]
